---
# create variables at workflow, job and step level
name: variables in python workflow
on: 
 push:
env:
   PYTHON_VERSION: 3.9
jobs:
  job1-workflow-variables:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup python ${{ env.PYTHON_VERSION }}        #workflow level variable
      #like in jenkins we use parameters = param.variable
      # in GitHub we use it like  ${{}}
      uses: actions/setup-python@v5
      with:
       python-version: ${{ env.PYTHON_VERSION }}          #workflow level variable
  job2-job-variables:
   runs-on: ubuntu-latest
   env:
     JOB_PYTHON_VERSION: 3.8
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup python ${{ env.JOB_PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
       python-version: ${{ env.MYJOB_PYTHON_VERSION }}
  job3-step-variables:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup python
      env:
       STEP-PYTHON-VERSION: 3.12
      uses: actions/setup-python@v5
      with:
       python-version: ${{ env.STEP-PYTHON-VERSION }}     #step level variable
    - name: Print app message
      env:
       APPLICATION: python
      run: echo "The application name is $APPLICATION"
